<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="1.933">
  <properties />
            <testcase name="tearDown" time="0.000" classname="com.w2a.testcases.LoginTest">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.w2a.base.Page.quit(Page.java:138)
  com.w2a.testcases.BaseTest.tearDown(BaseTest.java:15)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="loginTest" time="1.933" classname="com.w2a.testcases.LoginTest" />
      
</testsuite>
